name: fnet2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - optuna=2.9.1
  - pip=21.0.1
  - cuda91=1.0
  - pytorch=1.8.0
  - torchvision=0.9.0
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - pandas=1.2.3
  - tqdm=4.59.0
  - scikit-learn=0.24.2
  - scipy=1.1.0
  - tifffile=0.15
  - pip:
    - argschema
    - opencv-python==4.5.2.52
    - nd2reader==3.2.3

